### ISSUE TITLE
addNames should be POST

### ISSUE THREAD

**Issue by rvennam** [IBM-Cloud/get-started-java#1]

**Comment by rvennam** [comment]
@opiethehokie Can you review the latest commits? I removed the servlets and wrote an API instead.

**Comment by opiethehokie** [comment]
I like this better than just having the servlet.

I would suggest renaming `CloudantStore` to `CloudantVisitorStore` and I think VisitorStoreFactory needs some work. On every HTTP request isn't VCAP_SERVICES getting parsed again? Seems like the same DB connection could be reused, or am I missing something?

And `databaseName` in `CloudantStore` should be final.

**Comment by rvennam** [comment]
Done.
